# Generated by Django 3.2.9 on 2021-11-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculadoraNutricional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
